# Use the official Node.js image as the base image
FROM node:14

# Create a working directory
RUN mkdir -p /usr/src/app

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the TypeScript files
RUN npm run build

# Expose the port for the API to listen on
EXPOSE 5000

# Start the API
CMD ["npm", "start"]
